export default {
  accordion: { title: "Accordion" },
  avatar: { title: "Avatar" },
  button: { title: "Button" },
  calendar: { title: "Calendar" },
  card: { title: "Card" },
  checkbox: { title: "Checkbox" },
  chip: { title: "Chip" },
  "clear-button": { title: "ClearButton" },
  combobox: { title: "Combobox" },
  "date-picker": { title: "DatePicker" },
  dialog: { title: "Dialog" },
  drawer: { title: "Drawer" },
  field: { title: "Field" },
  input: { title: "Input" },
  loader: { title: "Loader" },
  menu: { title: "Menu" },
  "number-field": { title: "NumberField" },
  popover: { title: "Popover" },
  progress: { title: "Progress" },
  radio: { title: "Radio" },
  "scroll-area": { title: "ScrollArea" },
  select: { title: "Select" },
  separator: { title: "Separator" },
  slider: { title: "Slider" },
  switch: { title: "Switch" },
  table: { title: "Table" },
  "data-table": { title: "Data Table" },
  tabs: { title: "Tabs" },
  textarea: { title: "Textarea" },
  "theme-toggle": { title: "ThemeToggle" },
  toast: { title: "Toast" },
  "toggle-group": { title: "ToggleGroup" },
  tooltip: { title: "Tooltip" },
};
