export default {
  accordion: { title: "Accordion" },
  avatar: { title: "Avatar" },
  button: { title: "Button" },
  card: { title: "Card" },
  checkbox: { title: "Checkbox" },
  chip: { title: "Chip" },
  "clear-button": { title: "ClearButton" },
  combobox: { title: "Combobox" },
  dialog: { title: "Dialog" },
  drawer: { title: "Drawer" },
  field: { title: "Field" },
  input: { title: "Input" },
  loader: { title: "Loader" },
  popover: { title: "Popover" },
  radio: { title: "Radio" },
  select: { title: "Select" },
  separator: { title: "Separator" },
  slider: { title: "Slider" },
  switch: { title: "Switch" },
  tabs: { title: "Tabs" },
  textarea: { title: "Textarea" },
  "toggle-group": { title: "ToggleGroup" },
  tooltip: { title: "Tooltip" },
};
